DROP DATABASE IF EXISTS MMM_ANOMALIA;
CREATE DATABASE MMM_ANOMALIA;
USE MMM_ANOMALIA;

CREATE TABLE EMPRESA (
  idEMPRESA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  PRIMARY KEY(idEMPRESA)
);

CREATE TABLE TIPO_LESAO (
  idTIPO_LESAO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  PRIMARY KEY(idTIPO_LESAO)
);

CREATE TABLE FUNCAO (
  idFUNCAO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NULL,
  PRIMARY KEY(idFUNCAO)
);

CREATE TABLE SEVERIDADE (
  idSEVERIDADE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  GRAU_SEVERIDADE VARCHAR(50) NOT NULL,
  PRIMARY KEY(idSEVERIDADE)
);

CREATE TABLE PARTE_CORPO (
  idPARTE_CORPO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  PRIMARY KEY(idPARTE_CORPO)
);

CREATE TABLE CLASSIFICACAO_ANOMALIA (
  idCLASSIFICACAO_ANOMALIA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  PRIMARY KEY(idCLASSIFICACAO_ANOMALIA)
);

CREATE TABLE COLABORADOR (
  idCOLABORADOR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  FUNCAO_idFUNCAO INTEGER UNSIGNED NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  MATRICULA INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idCOLABORADOR),
  INDEX COLABORADOR_FKIndex1(FUNCAO_idFUNCAO),
  FOREIGN KEY(FUNCAO_idFUNCAO)
    REFERENCES FUNCAO(idFUNCAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE CONTRATO (
  idCONTRATO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  EMPRESA_idEMPRESA INTEGER UNSIGNED NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  PRIMARY KEY(idCONTRATO),
  INDEX CONTRATO_FKIndex1(EMPRESA_idEMPRESA),
  FOREIGN KEY(EMPRESA_idEMPRESA)
    REFERENCES EMPRESA(idEMPRESA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE ANOMALIA (
  idANOMALIA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CLASSIFICACAO_ANOMALIA_idCLASSIFICACAO_ANOMALIA INTEGER UNSIGNED NOT NULL,
  CONTRATO_idCONTRATO INTEGER UNSIGNED NOT NULL,
  DESCRICAO VARCHAR(50) NULL,
  DATA_OCORRENCIA DATE NULL,
  PRIMARY KEY(idANOMALIA),
  INDEX ANOMALIA_FKIndex1(CONTRATO_idCONTRATO),
  INDEX ANOMALIA_FKIndex2(CLASSIFICACAO_ANOMALIA_idCLASSIFICACAO_ANOMALIA),
  FOREIGN KEY(CONTRATO_idCONTRATO)
    REFERENCES CONTRATO(idCONTRATO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CLASSIFICACAO_ANOMALIA_idCLASSIFICACAO_ANOMALIA)
    REFERENCES CLASSIFICACAO_ANOMALIA(idCLASSIFICACAO_ANOMALIA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE COLABORADOR_CONTRATO (
  COLABORADOR_idCOLABORADOR INTEGER UNSIGNED NOT NULL,
  CONTRATO_idCONTRATO INTEGER UNSIGNED NOT NULL,
  INICIO_VINCULO DATE NOT NULL,
  FIM_VINCULO DATE NULL,
  PRIMARY KEY(COLABORADOR_idCOLABORADOR, CONTRATO_idCONTRATO),
  INDEX COLABORADOR_has_CONTRATO_FKIndex1(COLABORADOR_idCOLABORADOR),
  INDEX COLABORADOR_has_CONTRATO_FKIndex2(CONTRATO_idCONTRATO),
  FOREIGN KEY(COLABORADOR_idCOLABORADOR)
    REFERENCES COLABORADOR(idCOLABORADOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(CONTRATO_idCONTRATO)
    REFERENCES CONTRATO(idCONTRATO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE COLABORADOR_AFETADO (
  COLABORADOR_idCOLABORADOR INTEGER UNSIGNED NOT NULL,
  ANOMALIA_idANOMALIA INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(COLABORADOR_idCOLABORADOR, ANOMALIA_idANOMALIA),
  INDEX COLABORADOR_has_ANOMALIA_FKIndex1(COLABORADOR_idCOLABORADOR),
  INDEX COLABORADOR_has_ANOMALIA_FKIndex2(ANOMALIA_idANOMALIA),
  FOREIGN KEY(COLABORADOR_idCOLABORADOR)
    REFERENCES COLABORADOR(idCOLABORADOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(ANOMALIA_idANOMALIA)
    REFERENCES ANOMALIA(idANOMALIA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE COLABORADOR_LESIONADO (
  COLABORADOR_AFETADO_ANOMALIA_idANOMALIA INTEGER UNSIGNED NOT NULL,
  COLABORADOR_AFETADO_COLABORADOR_idCOLABORADOR INTEGER UNSIGNED NOT NULL,
  TIPO_LESAO_idTIPO_LESAO INTEGER UNSIGNED NOT NULL,
  PARTE_CORPO_idPARTE_CORPO INTEGER UNSIGNED NULL,
  SEVERIDADE_idSEVERIDADE INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(COLABORADOR_AFETADO_ANOMALIA_idANOMALIA, COLABORADOR_AFETADO_COLABORADOR_idCOLABORADOR, TIPO_LESAO_idTIPO_LESAO),
  INDEX COLABORADOR_AFETADO_has_TIPO_LESAO_FKIndex1(COLABORADOR_AFETADO_COLABORADOR_idCOLABORADOR, COLABORADOR_AFETADO_ANOMALIA_idANOMALIA),
  INDEX COLABORADOR_AFETADO_has_TIPO_LESAO_FKIndex2(TIPO_LESAO_idTIPO_LESAO),
  INDEX COLABORADOR_LESIONADO_FKIndex3(SEVERIDADE_idSEVERIDADE),
  INDEX COLABORADOR_LESIONADO_FKIndex4(PARTE_CORPO_idPARTE_CORPO),
  FOREIGN KEY(COLABORADOR_AFETADO_COLABORADOR_idCOLABORADOR, COLABORADOR_AFETADO_ANOMALIA_idANOMALIA)
    REFERENCES COLABORADOR_AFETADO(COLABORADOR_idCOLABORADOR, ANOMALIA_idANOMALIA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(TIPO_LESAO_idTIPO_LESAO)
    REFERENCES TIPO_LESAO(idTIPO_LESAO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(SEVERIDADE_idSEVERIDADE)
    REFERENCES SEVERIDADE(idSEVERIDADE)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(PARTE_CORPO_idPARTE_CORPO)
    REFERENCES PARTE_CORPO(idPARTE_CORPO)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


